version: '3'
services:
   peer1:
      build: ./BlockChain/
      ports:
         - 10006:10006
      environment:
         - PEER_PORT=10006
         - PEER2=peer2:10007
         - PEER3=peer3:10008
         - PEER4=peer4:10009
   peer2:
      build: ./BlockChain/
      ports:
         - 10007:10007
      environment:
         - PEER_PORT=10007
         - PEER1=peer1:10006
         - PEER3=peer3:10008
         - PEER4=peer4:10009
   peer3:
      build: ./BlockChain/
      ports:
         - 10008:10008
      environment:
         - PEER_PORT=10008
         - PEER1=peer1:10006
         - PEER2=peer2:10007
         - PEER4=peer4:10009

   peer4:
      build: ./BlockChain/
      ports:
         - 10009:10009
      environment:
         - PEER_PORT=10009
         - PEER1=peer1:10006
         - PEER2=peer2:10007
         - PEER3=peer3:10008
