version: '3'

services:
  peer1:
    build: .
    command: npm start
    volumes:
      - :/usr/src/app
    ports:
      - "3000:3000"
    environment:
    - HOST=0.0.0.0
    - PORT=3000

  peer2:
    build: .
    command: npm start
    volumes:
      - :/usr/src/app
    ports:
      - "3001:3000"
    environment:
    - HOST=0.0.0.0
    - PORT=3000
